/dev/input/event1: EV_ABS       ABS_MT_TRACKING_ID   00005ba0
/dev/input/event1: EV_KEY       BTN_TOUCH            DOWN
/dev/input/event1: EV_KEY       BTN_TOOL_FINGER      DOWN
/dev/input/event1: EV_ABS       ABS_MT_POSITION_X    000003e8
/dev/input/event1: EV_ABS       ABS_MT_POSITION_Y    000007d0
/dev/input/event1: EV_ABS       ABS_MT_TOUCH_MINOR   00000004
/dev/input/event1: EV_SYN       SYN_REPORT           00000000
/dev/input/event1: EV_ABS       ABS_MT_TRACKING_ID   ffffffff
/dev/input/event1: EV_KEY       BTN_TOUCH            UP
/dev/input/event1: EV_KEY       BTN_TOOL_FINGER      UP
/dev/input/event1: EV_SYN       SYN_REPORT           00000000